# T2I-Bot-Skill AI Rig - Windows Auto-Start Installation Script
# Creates startup tasks, services, and auto-launch on Windows boot
# ANTICLAW-2 :: SOVEREIGN DEPLOYMENT

$ErrorActionPreference = "Continue"

# Configuration
$ProjectRoot = "E:\T2I-bot-skill"
$AppName = "T2I-Bot-Skill AI Rig"
$TaskName = "T2I-AutoStart"
$TaskPath = "\T2I-Bot-Skill\"
$NodePath = (Get-Command node).Source
$NpmPath = (Get-Command npm).Source

# Colors
function Write-Info { param($msg) Write-Host "[INFO] $msg" -ForegroundColor Cyan }
function Write-Success { param($msg) Write-Host "[SUCCESS] $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Error { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red }

# Banner
Clear-Host
Write-Host @"
╔════════════════════════════════════════════════════════════════════╗
║     T2I-Bot-Skill AI Rig - Windows Auto-Start Installer           ║
║     ANTICLAW-2 :: SOVEREIGN DEPLOYMENT                            ║
╚════════════════════════════════════════════════════════════════════╝
"@

Write-Info "Project Root: $ProjectRoot"
Write-Info "Node: $NodePath"
Write-Info "NPM: $NpmPath"
Write-Host ""

# Check if running as admin
$isAdmin = ([Security.Principal.WindowsPrincipal] `
    [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(`
    [Security.Principal.WindowsBuiltInRole] "Administrator")

if (-not $isAdmin) {
    Write-Error "This script must be run as Administrator!"
    Write-Host ""
    Write-Info "Right-click this PowerShell script and select 'Run as Administrator'"
    Write-Host ""
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Success "Running as Administrator ✓"
Write-Host ""

# Step 1: Create startup script
Write-Info "Creating startup script..."

$StartupScriptPath = "$ProjectRoot\start-rig.ps1"
$StartupScriptContent = @"
# T2I-Bot-Skill AI Rig Startup Script
# Auto-generated by install-windows-autostart.ps1

`$ErrorActionPreference = "Continue"
`$ProjectRoot = "$ProjectRoot"

# Set working directory
Set-Location `$ProjectRoot

# Check if Node modules are installed
if (-not (Test-Path "`$ProjectRoot\node_modules")) {
    Write-Host "[INFO] Installing Node dependencies..." -ForegroundColor Cyan
    npm install
}

# Start T2I Server
Write-Host "[INFO] Starting T2I Server on port 3000..." -ForegroundColor Yellow
Start-Process powershell -ArgumentList "-NoExit", "-Command", "cd '$ProjectRoot'; npm run dev"

# Wait for server to initialize
Start-Sleep -Seconds 5

# Start code-server (if installed)
if (Get-Command code-server -ErrorAction SilentlyContinue) {
    Write-Host "[INFO] Starting code-server on port 8080..." -ForegroundColor Yellow
    Start-Process code-server -ArgumentList "--config", "`$env:USERPROFILE\.config\code-server\config.yaml"
}

# Start OpenWebUI (if Docker is available)
if (Get-Command docker -ErrorAction SilentlyContinue) {
    Write-Host "[INFO] Checking Docker containers..." -ForegroundColor Yellow
    docker ps -a | Select-String "openwebui"
}

# Open browser after delay
Start-Sleep -Seconds 10
Write-Host "[INFO] Opening T2I-Bot-Skill in browser..." -ForegroundColor Green
Start-Process "http://localhost:3000"

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  T2I-Bot-Skill AI Rig is now running!" -ForegroundColor Yellow
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  T2I App:      http://localhost:3000" -ForegroundColor White
Write-Host "  code-server:  http://localhost:8080 (if running)" -ForegroundColor White
Write-Host "  OpenWebUI:    http://localhost:3001 (if running)" -ForegroundColor White
Write-Host ""
Write-Host "  Close this window to stop all services" -ForegroundColor Gray
Write-Host ""
"@

Set-Content -Path $StartupScriptPath -Value $StartupScriptContent
Write-Success "Startup script created: $StartupScriptPath ✓"
Write-Host ""

# Step 2: Create scheduled task for auto-start
Write-Info "Creating Windows Scheduled Task for auto-start..."

$TaskAction = New-ScheduledTaskAction -Execute "PowerShell.exe" `
    -Argument "-NoProfile -WindowStyle Hidden -File `"$StartupScriptPath`"" `
    -WorkingDirectory $ProjectRoot

$TaskTrigger = New-ScheduledTaskTrigger -AtLogOn

$TaskPrincipal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest

$TaskSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RunOnlyIfNetworkAvailable `
    -WakeToRun `
    -ExecutionTimeLimit (New-TimeSpan -Hours 24) `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1)

# Create task
try {
    # Create task folder first
    $null = Register-ScheduledTask `
        -TaskName $TaskName `
        -TaskPath $TaskPath `
        -Action $TaskAction `
        -Trigger $TaskTrigger `
        -Principal $TaskPrincipal `
        -Settings $TaskSettings `
        -Force `
        -ErrorAction Stop
    
    Write-Success "Scheduled task created: $TaskPath$TaskName ✓"
    Write-Host ""
    Write-Info "Task will auto-start T2I-Bot-Skill when you log in to Windows"
} catch {
    Write-Error "Failed to create scheduled task: $_"
    Write-Host ""
    Write-Info "You can manually run the startup script instead: $StartupScriptPath"
}

Write-Host ""

# Step 3: Create startup shortcut in Startup folder
Write-Info "Creating Startup folder shortcut..."

$StartupFolder = [Environment]::GetFolderPath("Startup")
$ShortcutPath = Join-Path $StartupFolder "T2I-Bot-Skill.lnk"

$WScriptShell = New-Object -ComObject WScript.Shell
$Shortcut = $WScriptShell.CreateShortcut($ShortcutPath)
$Shortcut.TargetPath = "PowerShell.exe"
$Shortcut.Arguments = "-NoProfile -NoExit -File `"$StartupScriptPath`""
$Shortcut.WorkingDirectory = $ProjectRoot
$Shortcut.IconLocation = "powershell.exe,0"
$Shortcut.Description = "T2I-Bot-Skill AI Rig Auto-Start"
$Shortcut.Save()

Write-Success "Startup shortcut created: $ShortcutPath ✓"
Write-Host ""

# Step 4: Create .env file if not exists
Write-Info "Checking environment configuration..."

$EnvFilePath = "$ProjectRoot\.env"
if (-not (Test-Path $EnvFilePath)) {
    $EnvContent = @"
# T2I-Bot-Skill AI Rig Environment Configuration
# Generated by install-windows-autostart.ps1

# Server Configuration
PORT=3000
NODE_ENV=development

# Admin Password (CHANGE THIS!)
ADMIN_PASSWORD=t2i-rig-admin

# OpenClaw Gateway Token (for AI provider access)
OPENCLAW_GATEWAY_TOKEN=your-openclaw-token-here

# AI Provider Keys (optional - add your own)
GEMINI_API_KEY=
OPENROUTER_API_KEY=

# Tunnel Configuration (optional)
NGROK_AUTHTOKEN=
CLOUDFLARE_TUNNEL_TOKEN=

# Database URLs
CHROMADB_URL=http://localhost:8000
OLLAMA_BASE_URL=http://localhost:11434
LMSTUDIO_BASE_URL=http://localhost:1234
"@
    
    Set-Content -Path $EnvFilePath -Value $EnvContent
    Write-Success "Environment file created: $EnvFilePath ✓"
    Write-Host ""
    Write-Warn "IMPORTANT: Edit .env and set your API keys and tokens!"
} else {
    Write-Info "Environment file already exists: $EnvFilePath"
}

Write-Host ""

# Step 5: Create OpenClaw/Moltbot hosting configuration
Write-Info "Setting up OpenClaw/Moltbot hosting configuration..."

$OpenClawConfigPath = "$ProjectRoot\config\openclaw-config.json"
$OpenClawConfig = @{
    gateway = @{
        port = 18789
        token = (New-Guid).Guid
        rate_limit = 100
        timeout = 30000
    }
    moltbot = @{
        enabled = $true
        dispatcher_port = 18790
        assessment_interval = 300  # 5 minutes
        resonance_sync = 83.33
        swarm_agents = @()
    }
    t2i = @{
        port = 3000
        socket_io_enabled = $true
        file_watcher = $true
    }
    services = @{
        lmstudio = @{ url = "http://localhost:1234"; enabled = $true }
        openwebui = @{ url = "http://localhost:3001"; enabled = $true }
        ollama = @{ url = "http://localhost:11434"; enabled = $true }
    }
}

$OpenClawConfig | ConvertTo-Json -Depth 10 | Set-Content -Path $OpenClawConfigPath
Write-Success "OpenClaw config created: $OpenClawConfigPath ✓"

Write-Host ""

# Step 6: Create Moltbot dispatcher script
Write-Info "Creating Moltbot Sovereign Swarm Dispatcher..."

$MoltbotScriptPath = "$ProjectRoot\scripts\moltbot-dispatcher.ps1"
$MoltbotScriptContent = @"
# Moltbot Sovereign Swarm Dispatcher
# ANTICLAW-2 Assessment Engine

`$ErrorActionPreference = "Continue"
`$ProjectRoot = "$ProjectRoot"

function Show-MoltbotHeader {
    Clear-Host
    Write-Host "╔════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║   MOLTBOT :: SOVEREIGN SWARM DISPATCHER              ║" -ForegroundColor Yellow
    Write-Host "║   ANTICLAW-2 Architectural Integrity Assessor        ║" -ForegroundColor Cyan
    Write-Host "╚════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""
}

function Get-ServiceStatus {
    Write-Host "[*] Checking service endpoints..." -ForegroundColor Yellow
    
    `$services = @(
        @{ Name = "T2I App"; Url = "http://localhost:3000/api/health" },
        @{ Name = "LM Studio"; Url = "http://localhost:1234" },
        @{ Name = "OpenWebUI"; Url = "http://localhost:3001" },
        @{ Name = "Ollama"; Url = "http://localhost:11434/api/tags" }
    )
    
    foreach (`$service in `$services) {
        try {
            `$response = Invoke-WebRequest -Uri `$service.Url -TimeoutSec 3 -ErrorAction Stop
            Write-Host "  [✓] `$(`$service.Name): ONLINE" -ForegroundColor Green
        } catch {
            Write-Host "  [✗] `$(`$service.Name): OFFLINE" -ForegroundColor Red
        }
    }
    Write-Host ""
}

function Invoke-MoltbotAssessment {
    Write-Host "[*] Running Moltbot Architectural Assessment..." -ForegroundColor Yellow
    
    # Check T2I structure
    `$requiredFiles = @(
        "server.ts",
        "src/App.tsx",
        "src/components/MonacoEditor.tsx",
        "src/components/AiProviderDashboard.tsx",
        "docker-compose.yml",
        "scripts/install-termux.sh"
    )
    
    `$score = 0
    `$total = `$requiredFiles.Count
    
    foreach (`$file in `$requiredFiles) {
        `$path = Join-Path `$ProjectRoot `$file
        if (Test-Path `$path) {
            `$score++
        }
    }
    
    `$percentage = [math]::Round((`$score / `$total) * 100, 2)
    `$resonance = [math]::Round(83.33 * (`$percentage / 100), 2)
    
    Write-Host ""
    Write-Host "  Architecture Integrity: `$score/`$total (`$percentage%)" -ForegroundColor Cyan
    Write-Host "  83.33Hz Resonance Sync: `$resonance Hz" -ForegroundColor Yellow
    Write-Host ""
    
    if (`$percentage -eq 100) {
        Write-Host "  [✓] RATING: 10.2/10 [ANTICLAW 2 HARDENED MASTER]" -ForegroundColor Green
    } elseif (`$percentage -ge 80) {
        Write-Host "  [✓] RATING: `$([math]::Round(`$percentage/10, 1))/10 [CONSOLE READY]" -ForegroundColor Yellow
    } else {
        Write-Host "  [!] RATING: `$([math]::Round(`$percentage/10, 1))/10 [NEEDS RECONSTRUCTION]" -ForegroundColor Red
    }
    
    Write-Host ""
}

function Start-SwarmAgent {
    param(`$AgentName)
    
    Write-Host "[*] Spawning swarm agent: `$AgentName..." -ForegroundColor Yellow
    
    # Placeholder for actual agent spawning logic
    Start-Sleep -Seconds 2
    
    Write-Host "  [✓] Agent `$AgentName spawned successfully" -ForegroundColor Green
    Write-Host ""
}

# MAIN LOOP
while (`$true) {
    Show-MoltbotHeader
    
    Write-Host "1. [STATUS] Check Service Endpoints" -ForegroundColor White
    Write-Host "2. [ASSESS] Run Moltbot Architectural Assessment" -ForegroundColor White
    Write-Host "3. [SPAWN] Launch Swarm Agent" -ForegroundColor White
    Write-Host "4. [SYNC] Neural Memory Sync (RAG)" -ForegroundColor White
    Write-Host "5. [BRAIN] Check Brain Directory" -ForegroundColor White
    Write-Host "Q. Exit" -ForegroundColor Yellow
    Write-Host ""
    
    `$choice = Read-Host "Awaiting Neural Command"
    Write-Host ""
    
    switch (`$choice) {
        "1" { Get-ServiceStatus }
        "2" { Invoke-MoltbotAssessment }
        "3" { 
            `$agent = Read-Host "Enter agent name"
            Start-SwarmAgent -AgentName `$agent
        }
        "4" {
            Write-Host "[*] Running RAG sync..." -ForegroundColor Yellow
            python "`$ProjectRoot\scripts\rag_processor.py" stats
            Write-Host ""
        }
        "5" {
            `$brainPath = "C:\Users\natra\.gemini\antigravity\brain"
            if (Test-Path `$brainPath) {
                Write-Host "[*] Brain directory contents:" -ForegroundColor Cyan
                Get-ChildItem -Path `$brainPath -Directory | Format-Table Name, LastWriteTime
            } else {
                Write-Host "[!] Brain directory not found" -ForegroundColor Red
            }
            Write-Host ""
        }
        "Q" { exit }
        "q" { exit }
    }
    
    Write-Host "Press any key to return to Moltbot Hub..." -ForegroundColor Gray
    `$null = [System.Console]::ReadKey()
}
"@

Set-Content -Path $MoltbotScriptPath -Value $MoltbotScriptContent
Write-Success "Moltbot dispatcher created: $MoltbotScriptPath ✓"

Write-Host ""

# Step 7: Create uninstall script
Write-Info "Creating uninstall script..."

$UninstallScriptPath = "$ProjectRoot\uninstall-autostart.ps1"
$UninstallScriptContent = @"
# T2I-Bot-Skill AI Rig - Uninstall Auto-Start
# Removes scheduled tasks and startup shortcuts

`$ErrorActionPreference = "Continue"
`$TaskName = "T2I-AutoStart"
`$TaskPath = "\T2I-Bot-Skill\"

Write-Host "Removing auto-start configuration..." -ForegroundColor Yellow

# Remove scheduled task
try {
    Unregister-ScheduledTask -TaskName `$TaskName -TaskPath `$TaskPath -Confirm:`$false -ErrorAction Stop
    Write-Host "[✓] Scheduled task removed" -ForegroundColor Green
} catch {
    Write-Host "[!] Scheduled task not found or already removed" -ForegroundColor Yellow
}

# Remove startup shortcut
`$StartupFolder = [Environment]::GetFolderPath("Startup")
`$ShortcutPath = Join-Path `$StartupFolder "T2I-Bot-Skill.lnk"

if (Test-Path `$ShortcutPath) {
    Remove-Item `$ShortcutPath -Force
    Write-Host "[✓] Startup shortcut removed" -ForegroundColor Green
} else {
    Write-Host "[!] Startup shortcut not found" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Auto-start configuration removed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "To completely uninstall T2I-Bot-Skill, also remove:" -ForegroundColor Yellow
Write-Host "  - E:\T2I-bot-skill directory"
Write-Host "  - Scheduled tasks in Task Scheduler"
Write-Host ""
"@

Set-Content -Path $UninstallScriptPath -Value $UninstallScriptContent
Write-Success "Uninstall script created: $UninstallScriptPath ✓"

Write-Host ""

# Step 8: Create README for auto-start
Write-Info "Creating auto-start documentation..."

$AutoStartReadme = @"
# T2I-Bot-Skill AI Rig - Windows Auto-Start

## What Was Installed

This installer has configured T2I-Bot-Skill to automatically start when you log in to Windows.

### Components Created:

1. **Startup Script**: `start-rig.ps1`
   - Starts T2I development server
   - Launches code-server (if installed)
   - Opens browser automatically

2. **Scheduled Task**: `T2I-Bot-Skill\T2I-AutoStart`
   - Runs at user logon
   - Runs with highest privileges
   - Auto-restarts on failure

3. **Startup Shortcut**: `T2I-Bot-Skill.lnk`
   - Located in Windows Startup folder
   - Alternative to scheduled task

4. **Configuration Files**:
   - `.env` - Environment variables
   - `config/openclaw-config.json` - OpenClaw/Moltbot settings
   - `scripts/moltbot-dispatcher.ps1` - Moltbot assessment tool

## How to Use

### Manual Start
```powershell
cd E:\T2I-bot-skill
.\start-rig.ps1
```

### Run Moltbot Dispatcher
```powershell
cd E:\T2I-bot-skill
.\scripts\moltbot-dispatcher.ps1
```

### Check Services
- T2I App: http://localhost:3000
- code-server: http://localhost:8080
- OpenWebUI: http://localhost:3001

## Configuration

### Change Auto-Start Behavior

1. Edit `start-rig.ps1` to customize what starts
2. Open Task Scheduler → Find "T2I-Bot-Skill\T2I-AutoStart"
3. Modify triggers or disable task

### Environment Variables

Edit `.env` file to configure:
- `ADMIN_PASSWORD` - Change default password
- `OPENCLAW_GATEWAY_TOKEN` - Set your token
- API keys for Gemini, OpenRouter, etc.

## Uninstall

To remove auto-start:
```powershell
cd E:\T2I-bot-skill
.\uninstall-autostart.ps1
```

## Troubleshooting

### Services not starting?
1. Check if Node.js is installed: `node --version`
2. Install dependencies: `npm install`
3. Check logs in PowerShell windows

### Browser not opening?
- Wait 15 seconds after startup
- Manually open http://localhost:3000

### Need help?
- Check README.md
- Run moltbot-dispatcher.ps1 for assessment
- Check brain directory: C:\Users\natra\.gemini\antigravity\brain

---

**ANTICLAW-2 :: SOVEREIGN DEPLOYMENT**
83.33Hz Resonance Sync Active
"@

Set-Content -Path "$ProjectRoot\AUTOSTART_README.md" -Value $AutoStartReadme
Write-Success "Documentation created: AUTOSTART_README.md ✓"

Write-Host ""
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  INSTALLATION COMPLETE!" -ForegroundColor Green
Write-Host "════════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "✓ Auto-start configured for Windows boot" -ForegroundColor Green
Write-Host "✓ Startup script: $StartupScriptPath" -ForegroundColor White
Write-Host "✓ Moltbot dispatcher: $MoltbotScriptPath" -ForegroundColor White
Write-Host "✓ OpenClaw config: $OpenClawConfigPath" -ForegroundColor White
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host "  1. Edit .env and set your API keys" -ForegroundColor White
Write-Host "  2. Run: npm install (if not already done)" -ForegroundColor White
Write-Host "  3. Restart to test auto-start, OR run .\start-rig.ps1 now" -ForegroundColor White
Write-Host "  4. Run Moltbot assessment: .\scripts\moltbot-dispatcher.ps1" -ForegroundColor White
Write-Host ""
Write-Host "Services will auto-start on next Windows login!" -ForegroundColor Cyan
Write-Host ""

# Ask if user wants to start now
$startNow = Read-Host "Start T2I-Bot-Skill AI Rig now? (y/n)"
if ($startNow -eq 'y' -or $startNow -eq 'Y') {
    Write-Host ""
    Write-Host "Starting T2I-Bot-Skill AI Rig..." -ForegroundColor Green
    & $StartupScriptPath
}
